# Artificial Neural Network

Activation fn -> 4 types, x=weighted sum
<br>
threshold fn -> 1(if x>=0), 0(if x<0) -> b/w 0 and 1
<br>
sigmoid fn -> 1/(1+e^-x) -> b/w 0 and 1, tells probabilty of y being bw 0 and 1
<br>
rectifier fn -> max(x,0)
<br>
hyperbolic tan (tanh) fn -> (1-e^-2x)/(1+e^-2x)

Perceptrons/single layer feed forward neural network -> feed input, output predicted, compared with actual value, cost calculated (sum of squared diff), given to neuron, weights updated, process repeated till cost is min -> back propagation

Gradient descent -> yhat vs cost, from a particular point, draw tangent, look at angle of slope, negative=downhill, positive=uphill -> which predicted y has least cost -> requires cost fn to be convex -> explained in prev cell (batch gradient descent)

Stochastic Gradient descent -> row-wise, avoid problem of finding local minimas instead of gloabl, has much higher fluctuations (one row at a time), faster(no need to load up the whole data), not deterministic

Backprop -> all weights updated simultaneously
<br>
Steps -> randomly initialise weights (small numbers close to 0) ->  input first obs in input layer (1 feature = 1 node) -> forward prop (neuron activated from left to right, impact of activation limited by weights, propagate till getting predicted result y) -> compare to actual result, measure error -> back prop (error prop from right to left, update weights acc to how much they are resp for the error, learning rate=by how much we update weights) -> repeat and update weights after each obs (Reinforcement learning/stochastic gd) or after a batch of obs (batch learning/batch gd) -> whole training set passed through ann = 1 epoch, redo more epochs

### Importing the libraries

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
df = pd.read_csv('Churn_Modelling.csv')

In [5]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

### Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))  # function = rectifier

### Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))  # get prediction+probability

## Part 3 - Training the ANN

### Compiling the ANN

In [19]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])  # optimizer=stochasticgd, loss=type of loss fn (binary classification = binary_crossentropy, non binary classification = crossentropy, softmax activation)

### Training the ANN on the Training set

In [20]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.6523 - accuracy: 0.6624
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5103 - accuracy: 0.7981
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4536 - accuracy: 0.8059
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4211 - accuracy: 0.8209
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4061 - accuracy: 0.8314
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3941 - accuracy: 0.8380
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3822 - accuracy: 0.8426
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3729 - accuracy: 0.8482
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3655 - accuracy: 0.8547
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3595 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [23]:
y_pred = ann.predict(sc.transform([[1.0, 0.0, 0.0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

1/1 [==============================] - 0s 41ms/step


In [25]:
print(y_pred > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [26]:
y_pred = ann.predict(X_test)

63/63 [==============================] - 0s 1ms/step


In [28]:
y_pred = (y_pred > 0.5)

In [29]:
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1521   74]
 [ 202  203]]


0.862